git:
  remote:
    upstream: 'mongodb/docs-bi-connector'
    tools: 'mongodb/docs-tools'
project:
  name: 'bi-connector'
  tag: 'bi-connector'
  url: 'http://docs.mongodb.com'
  title: "MongoDB Connector for BI"
  branched: true
system:
  tools:
    ref: HEAD
    pinned: false
  make:
    generated:
      - 'sphinx'
      - 'meta'
      - 'push'
      - 'integration'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
  files:
    - 'pdfs.yaml'
    - 'intersphinx.yaml'
    - 'push.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - htaccess: ['htaccess.yaml']
version:
  release: '1.1'
  branch: 'v1.1'
assets:
  - branch: master
    path: build/docs-tools
    repository: http://github.com/mongodb/docs-tools.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...
